 SELECT 
                sd.skills,
              ROUND( MEDIAN(salary_year_avg)) AS median_salary,
                count(jpf.*) AS demand_count
            FROM job_postings_fact AS jpf
            INNER JOIN skills_job_dim AS sjd
               on jpf.job_id = sjd.job_id
            inner join skills_dim AS sd
               on sjd.skill_id = sd.skill_id 
            WHERE 
                jpf.job_title_short = 'Data Engineer'
                AND jpf.job_work_from_home = True 
             group by
                     sd.skills
             HAVING COUNT(jpf.*)  > 100      
              ORDER BY median_salary DESC
            LIMIT 25 ;

┌────────────┬───────────────┬──────────────┐
│   skills   │ median_salary │ demand_count │
│  varchar   │    double     │    int64     │
├────────────┼───────────────┼──────────────┤
│ rust       │      210000.0 │          232 │
│ golang     │      184000.0 │          912 │
│ terraform  │      184000.0 │         3248 │
│ spring     │      175500.0 │          364 │
│ neo4j      │      170000.0 │          277 │
│ gdpr       │      169616.0 │          582 │
│ zoom       │      168438.0 │          127 │
│ graphql    │      167500.0 │          445 │
│ mongo      │      162250.0 │          265 │
│ fastapi    │      157500.0 │          204 │
│ bitbucket  │      155000.0 │          478 │
│ django     │      155000.0 │          265 │
│ crystal    │      154224.0 │          129 │
│ atlassian  │      151500.0 │          249 │
│ c          │      151500.0 │          444 │
│ typescript │      151000.0 │          388 │
│ kubernetes │      150500.0 │         4202 │
│ ruby       │      150000.0 │          736 │
│ airflow    │      150000.0 │         9996 │
│ css        │      150000.0 │          262 │
│ node       │      150000.0 │          179 │
│ redis      │      149000.0 │          605 │
│ vmware     │      148798.0 │          136 │
│ ansible    │      148798.0 │          475 │
│ jupyter    │      147500.0 │          400 │
└────────────┴───────────────┴──────────────┘
  25 rows                         3 columns

--------------------------------------------------------------





